language: java

jdk:
  - oraclejdk8
  - openjdk7

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ldap-utils

script: mvn -Popendj test -B

notifications:
  irc: "irc.freenode.org#lsc-project"
